name: berna_libary
description: An app to listen music and podcasts.

publish_to: 'none'

version: 0.0.1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.4.1
  firebase_auth: ^4.2.5
  flutter_modular: ^5.0.3
  modular_bloc_bind: ^1.0.1
  flutter_bloc: ^8.1.1
  dartz: ^0.10.1
  google_fonts: ^3.0.1
  font_awesome_flutter: ^10.3.0
  shared_preferences: ^2.0.16
  rive: ^0.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  bloc_test: ^9.0.0
  mocktail: ^0.3.0

flutter:

  uses-material-design: true
  assets:
    - assets/animations/
    - assets/images/
